fix: update workflows to fix errors (#22)
* fix: add pull request read permission to workflow

* fix: continue on error in the download generated files phase

* fix: do not run build_runner if it is not a dependency

* ci: integrate melos to the test and analysis workflow

* fix: codecov coverage workflow code

* fix: create combined lcov file to find and merge separate files

* refactor: update melos test commands for separate dart and flutter test runs

* fix: disable codecov coverage upload funtionality temporary

* fix: update upload artifact action and optimize the flow

* fix: flutter channel name for artifact uploading job

* fix: update flutter channel and version parameters for documentation action

diff --git a/melos.yaml b/melos.yaml
--- a/melos.yaml
+++ b/melos.yaml
@@ -5,30 +5,36 @@ packages:
   - packages/*
   - packages/*/*
   - packages/*/*/*
+  - packages/*/packages/*
+  - packages/**/example
 
 command:
   version:
     linkToCommits: true
     workspaceChangelog: false
+  bootstrap:
+    hooks:
+      post: melos run format
 
 scripts:
   format: |
-    dart format --set-exit-if-changed --line-length 80 packages/
+    dart format --set-exit-if-changed --line-length 80 .
 
   analyze: |
-    # Ensure Dart SDK and packages are up-to-date
-    echo "Updating Dart SDK and packages..."
-    flutter pub get
-
-    # Run Dart analysis with detailed output
-    echo "Analyzing Dart files in the packages directory:"
-    dart analyze --fatal-infos --fatal-warnings packages/
+    dart analyze --fatal-infos --fatal-warnings
 
   format-analyze: |
     melos run format && melos run analyze
 
-  test: |
-    very_good test -r --test-randomize-ordering-seed random --coverage
+  test: >
+    melos run test:dart &&
+    melos run test:flutter
+  test:dart: >
+    melos exec --no-flutter --concurrency=1 --fail-fast --dir-exists=test -- "
+      dart test --coverage=coverage &&
+      dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage
+    "
+  test:flutter: melos exec --flutter --concurrency=1 --fail-fast --dir-exists=test -- flutter test --coverage
 
   open-coverage: |
     original_dir=$(pwd)
@@ -49,3 +55,13 @@ scripts:
     melos run test
     echo "Tests completed. Opening coverage reports..."
     melos run open-coverage
+
+  generate: |
+    echo "Checking for build_runner availability..."
+    if dart pub global list | grep -q "build_runner"; then
+      echo "build_runner is available. Running code generation..."
+      dart run build_runner build --delete-conflicting-outputs
+    else
+      echo "Error: build_runner is not available. Please ensure it's installed in your project."
+      exit 1
+    fi
